log-level: INFO
show-codes: false
pattern: '§8{0,time,EEE hh:mm:ss a}§r [{1}] {2}' # 0 = Record Date, 1 = Level Name, 2 = Message, 3 = Level Value, 4 = Server Timestamp
levels: # 0 = Level Name
  SEVERE:  '§c SEVERE§r'
  WARNING: '§eWARNING§r'
  INFO:    '§8   INFO§r'
  CONFIG:  '§3 CONFIG§r'
  FINE:    '§6   FINE§r'
  FINER:   '§6  FINER§r'
  FINEST:  '§6 FINEST§r'
  (default): '{0}'
reload: '§f-> §2Reloaded §7{1} plugin'
format-code: '§'
version: @VERSION@